# Robot Parameters

# base_link_mass: 2.0 # Revisit alater
base_length: 0.204
base_width: 0.154
base_height: 0.092
base_link_offset: -0.074
base_wheel_gap_z: 0.06
base_collision: false

wheel_mass: 0.033         # 33g
wheel_radius: 0.034       # 6.8cm wheelDia
wheel_offset_z: 0.039    # 6.4cm from base_link
wheel_thickness: 0.02     # 2cm 
wheel_separation: 0.1934  # 19.34cm

caster_wheel_mass: 0.04       # 40g
caster_wheel_radius: 0.0105   # 2.1cm casterHeight
caster_wheel_thickness: 0.02
# caster_wheel_seperation: 0.42
caster_offset_z: -0.062  # From Robot Center
caster_offset_x: 0.07967 #Must be -ve if behind base_link

# Sensor dimensions

lidar_mass: 0.050
lidar_radius: 0.05
lidar_height: 0.1
lidar_offset_z: 0.08

camera_mass: 0.050
camera_length: 0.05
camera_width: 0.05
camera_height: 0.05
camera_offset_z: 0.05
camera_offset_x: 0.08

imu_mass: 0.050
imu_length: 0.05
imu_width: 0.05
imu_height: 0.05
imu_offset_z: 0.03
imu_offset_x: 0.05